name: Deploy insuregeini-web to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write SSH key to file
        run: |
          printf '%s\n' "${{ secrets.EC2_KEY }}" > ./chathura_ec2.pem
          chmod 600 ./chathura_ec2.pem

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: 22
          key_path: ./chathura_ec2.pem
          script: |
            # Navigate to frontend repo
            cd Insuregeini_Web

            # Pull latest changes
            git pull origin main

            # Install dependencies
            npm install

            pm2 restart insuregeini-web

            # Copy built files to Nginx www folder (adjust paths as needed)
            sudo rm -rf /var/www/insuregeini-web/*
            sudo cp -r dist/* /var/www/insuregeini-web/

            # Reload Nginx to serve updated files
            sudo systemctl reload nginx

      - name: Clean up SSH key
        run: rm ./chathura_ec2.pem
